#!/usr/bin/env bash

lein uberjar

aws lambda update-function-code \
  --region $1 \
  --function-name LambdaDemo \
  --zip-file fileb://./target/lambda-demo-0.1.0-SNAPSHOT-standalone.jar \
  --publish
